name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get


      - name: Analyze project source
        run: dart analyze

      - name: Build executable
        run: dart compile exe --target-os=linux ./bin/tables_puree.dart -o ./table-puree 
    
      - name: Compress the executable
        run: sudo apt install zip; zip -9 ./table-puree-linux.zip ./table-puree 
         
      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./table-puree-linux.zip
      
  build_windows:
      runs-on: windows-2022
      needs: build_linux
      permissions: 
        contents: write
      steps:
        - uses: actions/checkout@v4

        - uses: dart-lang/setup-dart@v1

        - name: Install dependencies
          run: dart pub get


        - name: Analyze project source
          run: dart analyze

        - name: Build executable
          run: dart compile exe --target-os=windows ./bin/tables_puree.dart -o ./table-puree.exe 
        
        - name: Upload windows build artifact
          uses: actions/upload-artifact@v4
          with:
            name: windows-build
            path: ./table-puree.exe
  
  create_release:
    name: Create Release
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: ./

      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          
          files: |
            ./table-puree-linux.zip
            ./table-puree-windows.exe

      
        